import esbuild from 'esbuild';
import path from 'path';
import process from 'process';
import { createRequire } from 'module';
import builtins from 'builtin-modules';
import { execSync } from 'child_process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const runImporter = () => {
    execSync('npm run gen:imports', { stdio: 'inherit' });
};

const require = createRequire(import.meta.url);
const tsInjexPackageDir = path.dirname(
    require.resolve('ts-injex/package.json'),
);
const tsInjexDistDir = path.join(tsInjexPackageDir, 'dist');

const importerPlugin = {
    name: 'run-importer',
    setup(build) {
        build.onStart(() => {
            console.log('Running importer...');
            runImporter();
        });
    },
};

const tsInjexAliasPlugin = {
    name: 'ts-injex-src-alias',
    setup(build) {
        build.onResolve({ filter: /^src\// }, (args) => {
            if (
                !args.importer.includes(
                    `${path.sep}node_modules${path.sep}ts-injex${path.sep}`,
                )
            ) {
                return;
            }

            const relativeImportPath = args.path.slice(4);
            const resolvedPath = path.join(
                tsInjexDistDir,
                path.extname(relativeImportPath) === ''
                    ? `${relativeImportPath}.js`
                    : relativeImportPath,
            );

            return { path: resolvedPath };
        });
    },
};

const prod = process.argv[2] === 'production';
const dev = process.argv[2] === 'development';

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'build/main.js',
    plugins: [tsInjexAliasPlugin, importerPlugin],
});

if (prod || dev) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
