name: Auto Changelog & Release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_prerelease: ${{ steps.release.outputs.release_prerelease }}
      release_tag: ${{ steps.release.outputs.release_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release
        id: release
        uses: https://git.0xmax42.io/actions/auto-changelog-release-action@v1
        with:
          token: ${{ secrets.GITEA_TOKEN }}
          version_file: package.json
          version_regex: '"version"\s*:\s*"([^"]+)"'
          patch_patterns: |
            ^chore\(deps\):

